title: "Donier Gastronomie"

lang: "fi"

permalink: /:title/

exclude: [Makefile, tidy-config.txt]

defaults:
  -
    scope:
      path: ""
    values:
      lang: "fi"
      langurl: "/"
      order: 1
      layout: "default"
  -
    scope:
      path: "en"
    values:
      lang: "en"
      langurl: "/en/"
      order: 2
#  -
#    scope:
#      path: "sv"
#    values:
#      lang: "sv"
#      langurl: "/sv/"
#      order: 2

t:
  team:
    fi: "Ihmiset"
    en: "Team"
    sv: "Team"
  products:
    fi: "Tuotteet"
    en: "Products"
    sv: "Produkter"
  contact:
    fi: "Yhteystiedot"
    en: "Contact"
    sv: "Kontakta"
